trigger:
  branches:
    include:
      - master
      - "*"

variables:
  poolName: 'Self-Hosted'

pool:
  name: $(poolName)

stages:
  - stage: Build
    displayName: "Build and Test"
    jobs:
      - job: Build
        displayName: "Restore, Build, and Test"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              version: "8.x"

          - script: dotnet restore "OTAssessment.sln"
            displayName: "Restore dependencies"

          - script: dotnet build "OTAssessment.sln" --no-restore --configuration Release
            displayName: "Build"

