services:
  ot-assessment-api:
    build:
      context: .
      dockerfile: OTAssessment/Dockerfile
    container_name: ot-assessment-api
    environment:
      - REFERENCE_DB__SERVER=mssql-server
      - REFERENCE_DB__DATABASE_NAME=OTAssessment
      - REFERENCE_DB__USER=sa
      - REFERENCE_DB__PASSWORD=$tr0ngP@55w0rD!
    ports:
      - "5000:80"
    networks:
      - ot-assessment-network

  ubuntu-agent:
    image: ubuntu:latest
    container_name: ubuntu-agent
    restart: always
    volumes:
      - .:/workspace
      - ./docker-scripts/ubuntu-agent/install-agent.sh:/install-agent.sh
      - agent-data:/home/ubuntu/agent
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - AZURE_PERSONAL_TOKEN=${AZURE_PERSONAL_TOKEN}
      - AZURE_AGENT_POOL=${AZURE_AGENT_POOL}
      - AZURE_COMPANY_URL=${AZURE_COMPANY_URL}
    entrypoint: ["/bin/bash", "-c", "/install-agent.sh && tail -f /dev/null"]
    user: "root"
    privileged: true
  
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$tr0ngP@55w0rD!
    ports:
      - "1433:1433"
    networks:
      - ot-assessment-network
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:7.2-alpine
    container_name: redis-tls
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./tls:/tls
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - ot-assessment-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=$tr0ngP@55w0rD!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ot-assessment-network

volumes:
  agent-data:
  rabbitmq_data:
    driver: local
  mssql_data:
    driver: local
    
networks:
  ot-assessment-network:
    name: shared-network
    driver: bridge